### ISSUE TITLE
UnicodeDecodeError with generation Cyrillic text dataset

### ISSUE THREAD

**Issue by IgorSondors** [Belval/TextRecognitionDataGenerator#115] opened 2020-01-20 10:01 UTC
Hello, I trying to generate dataset for Russian OCR, and I have some problems with unicode encoding. I use Cyrillic supporting fonts (fonts\ru folder), and I created Russian dictionary ru.txt . When I try trdg -l ru -c 10 -w 1, I can only receive digits and punctuation marcs. 
Examples:
![16 09 1994_3](https://user-images.githubusercontent.com/44669029/72716215-e7dc8e80-3b82-11ea-9e9a-0672723f351b.jpg)
![ 03           _8](https://user-images.githubusercontent.com/44669029/72716274-fc208b80-3b82-11ea-9740-6482e1558048.jpg)
If I trying to use my dictionary with command trdg -i C:\Users\sondors\.conda\envs\synth\Lib\site-packages\trdg\dicts\ru.txt -l ru -c 10 -w 1, there is en error:

(synth) C:\Users\sondors\Desktop\synth>trdg -i C:\Users\sondors\.conda\envs\synth\Lib\site-packages\trdg\dicts\ru.txt -l ru -c 10 -w 1
Missing modules for handwritten text generation.
Traceback (most recent call last):
  File "c:\users\sondors\.conda\envs\synth\lib\runpy.py", line 195, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sondors\.conda\envs\synth\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sondors\.conda\envs\synth\Scripts\trdg.exe\__main__.py", line 7, in <module>
  File "c:\users\sondors\.conda\envs\synth\lib\site-packages\trdg\run.py", line 311, in main
    strings = create_strings_from_file(args.input_file, args.count)
  File "c:\users\sondors\.conda\envs\synth\lib\site-packages\trdg\string_generator.py", line 17, in create_strings_from_file
    lines = [l[0:200] for l in f.read().splitlines() if len(l) > 0]
  File "c:\users\sondors\.conda\envs\synth\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 11: invalid continuation byte
OS: Windows
environment: python=3.6 with trdg pip installation 

I was struggled some time with adding 'utf-8-sig' encoding-decoding in .py files but received no success. Any suggestions how to make this process properly?

**Comment by Belval** [comment] 2020-01-20 12:57
My guess would be that the dictionary file is encoded using something else than UTF-8, probably windows-1252.

You can download notepad++ and convert the encoding to UTF-8 and it should work, or at least, show you the invalid characters.

See: https://superuser.com/questions/1163753/converting-text-file-to-utf-8-on-windows-command-prompt

Also, if you can share your `ru.txt` I would not mind trying to reproduce the issue on my side.

**Comment by IgorSondors** [comment] 2020-01-20 13:43
Thanks for your answer. I'll try this today and leave my feedback
[ru.txt](https://github.com/Belval/TextRecognitionDataGenerator/files/4086423/ru.txt)

**Comment by Belval** [comment] 2020-01-20 13:46
The encoding of your file is windows-1251* not windows-1252, if you convert it to UTF-8 it will work.

**Comment by IgorSondors** [comment] 2020-01-20 20:06
Belval, thank you very much. Everything is working fine

**Comment by Belval** [comment] 2020-01-20 20:15
Great, I will close this issue. Feel free to reopen if you encounter another problem.

**Closed by Belval** 2020-01-20 20:15 UTC

**Comment by kadmor** [comment] 2023-03-14 06:01
Hello, does anyone have a list of Russian fonts?
Because some fonts turn into squares for me.
![четырёхметровой_9](https://user-images.githubusercontent.com/44403458/224909961-c0d63423-0b72-45b5-b96b-fc5fa5266c3f.jpg)
