### ISSUE TITLE
how to set the distance between words?

### ISSUE THREAD

**Issue by yulinxuanzhi** [Belval/TextRecognitionDataGenerator#22] opened 2018-09-29 07:45 UTC
Given the generated text lines, I found the gap between words is pretty large, could you tell me how to decrease the gap? Thank you.

**Comment by Belval** [comment] 2018-09-29 14:47
Can you provide some examples? There is no parameter to tune space width but I would be willing to look it up.

(You can just drag and drop images in the GitHub textbox)

**Comment by yulinxuanzhi** [comment] 2018-09-30 01:17
![00_04496_32](https://user-images.githubusercontent.com/18739799/46251847-634b9580-c491-11e8-8b75-fd78b8ea93ac.jpg)
Just like this, it is generated with default parameters

**Comment by Belval** [comment] 2018-09-30 19:07
This is caused by the wordlist, it does not contain words but characters and since each word is split with a space it creates this.

I could get a better wordlist made actual Chinese words or add a parameter to remove spacing.

Which would you prefer?

**Comment by yulinxuanzhi** [comment] 2018-10-02 02:19
I want to generate  text lines with linguistic data not random text, the every line of my cn.txt is a sentence, and no extra space between Chinese characters(for Chinese, it don't need to).  So a better wordlist can deal with this?

**Comment by Belval** [comment] 2018-10-02 02:59
Yes, currently when you set the generated text length it will pick X random characters in the wordlist and print them with space in between.

I can definitely just remove spacing when dealing with asian languages if that would solve the issue.

**Comment by yulinxuanzhi** [comment] 2018-10-03 01:08
Thanks for your help.

**Comment by savort** [comment] 2018-12-17 02:15
@Belval could you set a parameter to define the distance between words?

**Comment by Belval** [comment] 2018-12-17 13:35
@savort I have added the `-sw`, `--space_width` parameter, which is a multiplier applied to your font's space width.

Here is the result with size 1, 1.5 and 4 respectively:

![1](https://user-images.githubusercontent.com/5399488/50090479-a7b81900-01d6-11e9-8206-dc5fa83e4878.jpg)
![1 5](https://user-images.githubusercontent.com/5399488/50090481-aa1a7300-01d6-11e9-90f3-7aa02048a232.jpg)
![4](https://user-images.githubusercontent.com/5399488/50090490-adadfa00-01d6-11e9-893a-20c5b7b333a3.jpg)

Changes are available on the text-orientation-and-variable-spacing branch.

**Comment by Belval** [comment] 2018-12-24 19:50
See https://github.com/Belval/TextRecognitionDataGenerator/pull/29

**Comment by Belval** [comment] 2019-01-15 16:06
This is now in the master branch. Closing.

**Closed by Belval** 2019-01-15 16:06 UTC
